brew cask install betterzipql
brew cask install caffeine
brew cask install dropbox
brew cask install firefox
brew cask install flash-player
brew cask install growlnotify
brew cask install iterm2
brew cask install jumpcut
brew cask install little-snitch
brew cask install menubar-countdown
brew cask install mou
brew cask install qlstephen
brew cask install qlprettypatch
brew cask install sequel-pro
brew cask install skype
brew cask install spectacle
brew cask install teamviewer
brew cask install the-unarchiver
brew cask install vlc
brew cask install xquartz
